on: [push]

jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: read
      deployments: write
    name: Build & Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup Pacing-Quest Landing...
        run: echo "Startup build and deploy..."
      - name: Installing dependencies
        run: npm install
        working-directory: ./
      - name: Build Site
        run: SITE=${{ vars.SITE }} npm run build
        working-directory: ./
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 6d8a30b3ac9ba18554c27b86a4d4c98b
          projectName: pacing-quest
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: main
          # Optional: Change the working directory
          #workingDirectory: dist
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: "3"
